name: infra-dev

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write

env:
  BICEP_FILE: infra/bicep/main.bicep
  BICEP_PARAMS: infra/bicep/params/dev.parameters.json

jobs:
  deploy_infra_dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Validate infra (bicep)
        run: >
          az deployment group validate
          --resource-group "${{ vars.AZURE_RG_DEV }}"
          --template-file "${{ env.BICEP_FILE }}"
          --parameters @"${{ env.BICEP_PARAMS }}"
          --parameters sqlAdminPassword="${{ secrets.SQL_ADMIN_PASSWORD_DEV }}"
          --parameters jwtKey="${{ secrets.JWT_KEY_DEV }}"
          --parameters rabbitMqConnectionString="${{ secrets.RABBITMQ_CONNECTION_STRING_DEV }}"
          --parameters smtpPassword="${{ secrets.SMTP_PASSWORD_DEV }}"
          --parameters smtpUsername="${{ vars.SMTP_USERNAME_DEV }}"
          --parameters turnstileSecretKey="${{ secrets.TURNSTILE_SECRET_KEY_DEV }}"

      - name: Deploy infra (bicep)
        run: >
          az deployment group create
          --resource-group "${{ vars.AZURE_RG_DEV }}"
          --template-file "${{ env.BICEP_FILE }}"
          --mode Incremental
          --parameters @"${{ env.BICEP_PARAMS }}"
          --parameters sqlAdminPassword="${{ secrets.SQL_ADMIN_PASSWORD_DEV }}"
          --parameters jwtKey="${{ secrets.JWT_KEY_DEV }}"
          --parameters rabbitMqConnectionString="${{ secrets.RABBITMQ_CONNECTION_STRING_DEV }}"
          --parameters smtpPassword="${{ secrets.SMTP_PASSWORD_DEV }}"
          --parameters smtpUsername="${{ vars.SMTP_USERNAME_DEV }}"
          --parameters turnstileSecretKey="${{ secrets.TURNSTILE_SECRET_KEY_DEV }}"
